Support GE 4.0.x and 4.1.x (#65)
gitextensions/GitExtensions.GerritPlugin pull request #67
Opened 2023-01-18 16:34 UTC by lekhmanrus

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build related changes
- [x] Documentation
- [ ] Other: 

## What is the current behavior?
Gerrit plugin seems to be not working on GE 4.0.x

Issue Number: 65

## What is the new behavior?
Not sure, maybe I'm doing something wrong or there is something wrong with my setup, but I've checked Gerrit plugin v2.0.4 on `GitExtensions-Portable-4.0.1.15887-f2567dea2`, `GitExtensions-Portable-4.0.2.16100-25100ec1f` and `GitExtensions-Portable-4.1.0.16008-d5c8b9ba7` - it seems it works fine on all of these versions.
Changed readme file, so `GE v >= 4.0.1` should use `Gerrit plugin v >= 2.0.4`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2023-01-18 17:17 UTC, lekhmanrus commented
Hi @maraf,
Looks like the [AppVeyor error](https://ci.appveyor.com/project/gitextensions/gitextensions-gerritplugin/builds/45976429) is related to [gitextensions.extensibility](https://github.com/gitextensions/gitextensions.extensibility):
```
C:\Users\appveyor\.nuget\packages\gitextensions.extensibility\0.3.0.57\build\net5.0\GitExtensions.Extensibility.targets(34,9): error MSB3073: The command "powershell.exe -ExecutionPolicy Unrestricted 
```

Is it because something changed on the AppVeyor setup?

2023-01-18 21:23 UTC, maraf commented
> Is it because something changed on the AppVeyor setup?

It seems ok. I'll try to dig into it tomorrow. 

> `GitExtensions-Portable-4.1.0.16008-d5c8b9ba7` - it seems it works fine on all of these versions.

Yea, it is quite possible that it works at the moment, but a lot of stuff can happen before 4.1 is finally released. My experience is that most of the (my) plugins break even for Git Extensions feature releases. If it does not, we can happily use the current plugin release. The turning point is when Git Extensions requires a newer version of GitExtensions.Extensibility.

2023-01-25 13:34 UTC, maraf commented
Sorry for the delay. I can't anything why the build failed. The command line and parameters looks good. 
Might it be a trasient failure? I tried to run the build again.

2023-01-25 13:45 UTC, maraf commented
Rebuild passed 👍

2023-01-25 13:46 UTC, maraf requested changes
Please update https://github.com/gitextensions/GitExtensions.GerritPlugin/blob/master/src/GitExtensions.GerritPlugin/GitExtensions.GerritPlugin.csproj.user to target specific Git Extensions release for development

2023-02-01 09:16 UTC, maraf approved these changes
Thank you! 👏

2023-02-01 19:01 UTC, lekhmanrus commented
Hi @maraf,
Looks like we have some AppVeyor GitExtensions.Extensibility errors again:
```
C:\Users\appveyor\.nuget\packages\gitextensions.extensibility\0.1.0.31\build\net461\GitExtensions.Extensibility.targets(22,9): error MSB3073: The command "powershell.exe -ExecutionPolicy Unrestricted C:\Users\appveyor\.nuget\packages\gitextensions.extensibility\0.1.0.31\build\net461\..\..\tools\Download-GitExtensions.ps1 -ExtractRootPath C:\projects\gitextensions-gerritplugin\src\GitExtensions.GerritPlugin\..\..\..\gitextensions.shared -Version v4.0.2 -Source GitHub" exited with code 1. [C:\projects\gitextensions-gerritplugin\src\GitExtensions.GerritPlugin\GitExtensions.GerritPlugin.csproj]
Command exited with code 1
```

2023-02-02 19:51 UTC, maraf commented
@RussKie Any ideas what AppVeyor thinks? 

It seems transient and re-running the build succeeds.

2023-02-02 22:13 UTC, merged

2023-02-02 22:28 UTC, RussKie commented
Are you asking about this?
```
System.Net.WebException : The remote server returned an error : (403) Forbidden.
```

It could be GitHub's throttling, if we're pulling something during the build....

2023-02-03 09:17 UTC, maraf commented
> Are you asking about this?
> 
> ```
> System.Net.WebException : The remote server returned an error : (403) Forbidden.
> ```
> 
> It could be GitHub's throttling, if we're pulling something during the build....

Sir, please tell me where did you found the error message? All I can see is that powershell failed..

2023-02-03 10:06 UTC, pmiossec commented
https://ci.appveyor.com/project/gitextensions/gitextensions-gerritplugin/builds/46122898#L18

Line 18, just before the powershell failure in line 19.

2023-02-03 12:47 UTC, maraf commented
Thank you! I wasn't able to see it 🙂